### ISSUE TITLE
Crash with OutOfBoundsException

### ISSUE THREAD

**Issue by cryxli** [JSJBDEV/SuperCobblestoneFunnels#1]
## Observation

[crash-2020-12-13_14.00.54-server.txt](https://github.com/JSJBDEV/SuperCobblestoneFunnels/files/5684606/crash-2020-12-13_14.00.54-server.txt)

...while mining away with a diamond funnel. 

I did not reduce the number of mods, because the error very much looks independent of other mods.

## Setup

- Minecraft 1.13.4
- Fabric API 0.25.0+build.415-1.16
- Super Cobblestone Funnels 1.2

## Recreate

Setup a funnel. Easiest way to reproduce the OutOfBounds is to set up a Redstone contraption that pushes the produced or/block away.

The error happens usually somewhere between 32 and 96 Cobblestones generated. That said, it can take quite some time...

## Suggestion

There is something wrong with the look-up table (list, array, whatever) for the generated ores/blocks.

If I had to guess, I'd say, removal of cotton resources has lead to some side effects; e.g. only cobblestone funnel can be crafted because iron funnel requires a copper funnel, which no longer exists.

It is possible that the size of the look-up table hasn't been adjusted accordingly...

**Comment by JSJBDEV** [comment]
this probably doesnt exist anymore, but will reopen if it does
