### ISSUE TITLE
Copper and Bronze Funnels removed, but apparently no recipe for Iron Funnel?

### ISSUE THREAD

**Issue by Derpford** [JSJBDEV/SuperCobblestoneFunnels#2]
I can't seem to find the recipe for the Iron Funnel. Did you forget to change it when removing the copper/bronze funnels?

**Comment by elbermudatri** [comment]
Hello, I've been trying to figure out how to get to the recipes. I go to the config folder, right?  (If this is a stupid question, just know I've never programmed or configured something, so this is kinda new to me.) 
However, for this mod, it only shows me config, funnel_blocks, and funnel_blocks_weights under the config folder. When I open each, it doesn't show me any recipes but rather short texts like "minecraft: cobblestone," etc. Do I need a specific program to do this or... How were you able to do this?

**Comment by Derpford** [comment]
So, the config file is for changing what blocks will be *created* by the funnels. The recipes are not user-configurable; I had to go into the java class file for the funnel recipes, and change a line from `"scf:copper_funnel"` to `"scf:cobblestone_funnel"`. You can see the change I made here: https://github.com/JSJBDEV/SuperCobblestoneFunnels/pull/3/commits/76208733b7934fdb4155dc26314a98e071568f9b

As soon as the author accepts this "pull request", this change will be added to the code on GitHub, and from there all the mod author has to do is take what's on GitHub and compile that into a new version of the mod.

**Comment by Beethoven-n** [comment]
just added a pull request for a similar issue but wow, it looks like OP won't actually merge the request lol
is the mod abandoned already?
